services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"  # Expose MongoDB port
    networks:
      - mynetwork
  
  frontend:
    build: ./front
    container_name: react-app
    ports:
      - "5173:5173"  # Expose React app port
    networks:
      - mynetwork
    depends_on:
      - backend

  backend:
    build: ./back
    container_name: express-server
    ports:
      - "3000:3000"  # Expose Express app port
    depends_on:
      - mongodb
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Expose port 80 for NGINX (HTTP)
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount custom NGINX config
    depends_on:
      - frontend
      - backend


networks:
  mynetwork:
    driver: bridge
