version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-network

  backend:
    build:
      context: ./back
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - mern-network

  frontend:
    build:
      context: ./front
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
      - mongodb
    environment:
      - VITE_BACK_API=http://localhost:3000
    networks:
      - mern-network
    command: npm run start

# Volumes
volumes:
  mongo-data:

# Networks
networks:
  mern-network:
    driver: bridge
