version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
  

  backend:
    build:
      context: ./back  
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongodb


  frontend:
    build:
      context: ./front 
    container_name: frontend
    ports:
      - "90:80"
    depends_on:
      - backend
      - mongodb
  