services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"  # Expose MongoDB port
    networks:
      - mynetwork
  
  front:
    build: ./front
    container_name: react-app
    ports:
      - "5173:5173"  # Expose React app port
    networks:
      - mynetwork

  express:
    build: ./back
    container_name: express-server
    ports:
      - "3000:3000"  # Expose Express app port
    depends_on:
      - mongodb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
