apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back  
  template:
    metadata:
      labels:
        app: back 
    spec:
      containers:
        - name: back-container
          image: saxenarajat499/employ_backend:v1
          env:
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: JWT_SECRET
            - name: CLOUD_NAME
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: CLOUD_NAME 
            - name: CLOUD_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: CLOUD_API_KEY
            - name: CLOUD_API_SECRET
              valueFrom:
                configMapKeyRef:
                  name: env 
                  key: CLOUD_API_SECRET 
            - name: SERVER_PORT
              valueFrom:  
                configMapKeyRef:
                  name: env
                  key: SERVER_PORT
            - name: MONGO_HOST
              valueFrom:  
                configMapKeyRef:
                  name: env
                  key: MONGO_HOST
            - name: CORS 
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: CORS
          ports:
          - containerPort: 3000 
---
apiVersion: v1
kind: Service
metadata:
  name: back-service
spec:
  selector:
    app: back  
  ports:
    - port: 3000  
      name: back
      targetPort: 3000  
  type: NodePort
   